#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ice_nine
Version  : 0.11.2
Release  : 5
URL      : https://rubygems.org/downloads/ice_nine-0.11.2.gem
Source0  : https://rubygems.org/downloads/ice_nine-0.11.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
ice_nine
========
Deep freeze ruby objects
[![Gem Version](https://badge.fury.io/rb/ice_nine.svg)][gem]
[![Build Status](https://secure.travis-ci.org/dkubb/ice_nine.svg?branch=master)][travis]
[![Dependency Status](https://gemnasium.com/dkubb/ice_nine.svg)][gemnasium]
[![Code Climate](https://codeclimate.com/github/dkubb/ice_nine.png)][codeclimate]
[![Inline docs](http://inch-ci.org/github/dkubb/ice_nine.svg?branch=master)][inch]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ice_nine-0.11.2
gem spec %{SOURCE0} -l --ruby > rubygem-ice_nine.gemspec

%build
gem build rubygem-ice_nine.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ice_nine-0.11.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ice_nine-0.11.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/.pelusa.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/.rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/.ruby-gemset
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/Gemfile.devtools
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/TODO
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/benchmarks/speed.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/devtools.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/flay.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/flog.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/mutant.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/reek.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/roodi.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/config/yardstick.yml
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/ice_nine.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/core_ext/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/false_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/hash/state.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/module.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/nil_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/no_freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/numeric.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/range.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/rubinius.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/struct.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/freezer/true_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/support/recursion_guard.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/lib/ice_nine/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/integration/ice_nine/class_methods/deep_freeze_bang_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/integration/ice_nine/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/shared/array_deep_freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/shared/hash_deep_freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/shared/ice_nine_deep_freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/shared/no_freeze_deep_freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/shared/object_deep_freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/shared/range_deep_freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/support/config_alias.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/class_methods/deep_freeze_bang_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/core_ext/object/deep_freeze_bang_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/core_ext/object/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/array/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/class_methods/element_reader_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/false_class/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/hash/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/module/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/nil_class/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/no_freeze/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/numeric/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/object/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/range/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/struct/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/symbol/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/freezer/true_class/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/recursion_guard/frozen/guard_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/ice_nine/recursion_guard/object_set/guard_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ice_nine-0.11.2/spec/unit/object/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ice_nine-0.11.2.gemspec
