#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ice_nine
Version  : 0.11.1
Release  : 2
URL      : https://rubygems.org/downloads/ice_nine-0.11.1.gem
Source0  : https://rubygems.org/downloads/ice_nine-0.11.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
ice_nine
========
Deep freeze ruby objects
[![Gem Version](https://badge.fury.io/rb/ice_nine.svg)][gem]
[![Build Status](https://secure.travis-ci.org/dkubb/ice_nine.svg?branch=master)][travis]
[![Dependency Status](https://gemnasium.com/dkubb/ice_nine.svg)][gemnasium]
[![Code Climate](https://codeclimate.com/github/dkubb/ice_nine.png)][codeclimate]
[![Coverage Status](https://coveralls.io/repos/dkubb/ice_nine/badge.png?branch=master)][coveralls]
[![Inline docs](http://inch-ci.org/github/dkubb/ice_nine.svg?branch=master)][inch]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ice_nine-0.11.1
gem spec %{SOURCE0} -l --ruby > rubygem-ice_nine.gemspec

%build
gem build rubygem-ice_nine.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ice_nine-0.11.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ice_nine-0.11.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/CoreExt/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/CoreExt/Object/deep_freeze%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/CoreExt/Object/deep_freeze-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/CoreExt/cdesc-CoreExt.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/%5b%5d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Array/guarded_deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/BasicObject/cdesc-BasicObject.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/BasicObject/freeze_instance_variables-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/BasicObject/guarded_deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/FalseClass/cdesc-FalseClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Hash/State/cdesc-State.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Hash/freeze_key_value_pairs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Hash/guarded_deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Module/cdesc-Module.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/NilClass/cdesc-NilClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/NoFreeze/cdesc-NoFreeze.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/NoFreeze/guarded_deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Numeric/cdesc-Numeric.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Object/freeze_instance_variables-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Object/guarded_deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Range/cdesc-Range.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Range/guarded_deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Rubinius/cdesc-Rubinius.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Struct/cdesc-Struct.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/TrueClass/cdesc-TrueClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/cdesc-Freezer.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/const_lookup-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/deep_freeze%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/find-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/Freezer/guarded_deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/RecursionGuard/Frozen/cdesc-Frozen.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/RecursionGuard/Frozen/guard-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/RecursionGuard/ObjectSet/cdesc-ObjectSet.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/RecursionGuard/ObjectSet/guard-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/RecursionGuard/ObjectSet/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/RecursionGuard/cdesc-RecursionGuard.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/cdesc-IceNine.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/deep_freeze%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/IceNine/deep_freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/ice_nine-0.11.1/ri/page-TODO.ri
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/.pelusa.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/.rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/.ruby-gemset
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/Gemfile.devtools
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/TODO
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/benchmarks/speed.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/devtools.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/flay.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/flog.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/mutant.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/reek.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/roodi.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/config/yardstick.yml
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/ice_nine.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/core_ext/object.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/array.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/false_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/hash/state.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/module.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/nil_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/no_freeze.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/numeric.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/object.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/range.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/rubinius.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/struct.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/symbol.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/freezer/true_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/support/recursion_guard.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/lib/ice_nine/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/integration/ice_nine/class_methods/deep_freeze_bang_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/integration/ice_nine/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/shared/array_deep_freeze.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/shared/hash_deep_freeze.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/shared/ice_nine_deep_freeze.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/shared/no_freeze_deep_freeze.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/shared/object_deep_freeze.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/shared/range_deep_freeze.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/support/config_alias.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/class_methods/deep_freeze_bang_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/core_ext/object/deep_freeze_bang_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/core_ext/object/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/array/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/class_methods/element_reader_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/false_class/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/hash/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/module/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/nil_class/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/no_freeze/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/numeric/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/object/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/range/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/struct/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/symbol/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/freezer/true_class/class_methods/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/recursion_guard/frozen/guard_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/ice_nine/recursion_guard/object_set/guard_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ice_nine-0.11.1/spec/unit/object/deep_freeze_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/ice_nine-0.11.1.gemspec
